### ISSUE TITLE
Repository Impl Case Class

### ISSUE THREAD

**Issue by skokaina** [talan-labs/toast-tk-engine#101]

**Comment by skokaina** [comment]
On the webapp side, there's a collision between scala case class and java DAO bean RepositoryImpl:

```
io.toast.tk.dao.domain.impl.repository.RepositoryImpl cannot also be a controllers.mongo.RepositoryImpl
[warn] case repository:RepositoryImpl => {
[warn] ^
```

**Comment by skokaina** [comment]
fixed and merged in master

**Comment by skokaina** [comment]
it can be tested now

**Comment by NathCoco** [comment]
Tested Ok. 

Had to do :

$ git clone https://gitlab.talanlabs.com/sallah-kokaina/toast-tk-play-webapp.git
$ cd toast-tk-play-webapp
$ sbt
$ dist
$ exit (pour sortir du sbt)
$ cd /app/assets/
$ npm install
$ bower install
$ gulp
$ cd ../..
$ sbt run

And clean my browser then call the url "localhost:9000" and it works
