### ISSUE TITLE
Webapp Scenario deletion is unstable

### ISSUE THREAD

**Issue by babebridou** [talan-labs/toast-tk-engine#106]
deleting a scenario leads to an unstable situation: the selected node in the tree no longer exists and an angular exception is raised when the user tries to create a new scenario.

Some node deletions also fail with "Error: has child nodes!" even when they don't.

**Comment by skokaina** [comment]
fixed with following update
@tabkram: why do we need to keep track of selectedItem in self ?

-- <current fix done by adding delete>
function removeSelectedNode(){
              console.log("removing:", self.selectedNode);
              if(self.selectedNode != 0){
                  self.selectedTree.remove(self.selectedNode);  

```
                  delete self.selectedElementId;
                  delete self.selectedItem;
```

```
          } else {
               console.log("select a node:");
          } 
        }
```

##

**Comment by babebridou** [comment]
The bug now also occurs when you create a scenario, click on repository, click back on scenarios, and click on add a new scenario.

```
angular.js:12798 TypeError: Cannot read property '$parent' of undefined
at Object.getParentId (webix_debug.js:12574)
at Object.getParentId (webix_debug.js:10582)
at tree.layout.service.js:109
at Object.webix.ready (webix_debug.js:910)
at Object.saveConcernedNode (tree.layout.service.js:103)
at Scope.$scope.addNodeToParent (scenario.controller.js:95)
at fn (eval at compile (angular.js:13643), <anonymous>:4:253)
at expensiveCheckFn (angular.js:14625)
at callback (angular.js:24093)
at Scope.$eval (angular.js:16374)
```

**Comment by skokaina** [comment]
106_delete_it merged to master, other issues found for folder (tracked through issue 108)

**Comment by skokaina** [comment]
106_delete_it merged to master, other issues found for folder (tracked through issue #118)

**Comment by skokaina** [comment]
issue #118 fixed and merged in master
