### ISSUE TITLE
[SNCF] [Agent] Add proxy parameters

### ISSUE THREAD

**Issue by NathCoco** [talan-labs/toast-tk-engine#117]
The agent can not be connected if there is a proxy : 
- add in the parameters the proxy settings
- use the parameters proxy to call an URL

**Comment by NathCoco** [comment]
For example, the agent can not ping "http://www.google.com" if there is the SNCF proxy

**Comment by tabkram** [comment]
SSLHandshakeException is handled to enable trusting all certificates. this is needed sometime in intra-network for buisness context. see   **ssl-certificate** branch
This could be a part of _connexion from behind a proxy features_
