### ISSUE TITLE
Embed jdk8 & chromedriver in toast-web-agent

### ISSUE THREAD

**Issue by skokaina** [talan-labs/toast-tk-engine#127]

**Comment by skokaina** [comment]
The idea is to have chromedriver.exe included with the msi installer. 
The path to chrome driver will have to be set by default to the destination directory.
Nathan, do you think we could include this one for next week release ?

**Comment by NathCoco** [comment]
Yes it is possible. 

Which version of the chromedriver do you want ? Is the 2.25 fine ? (https://sites.google.com/a/chromium.org/chromedriver/downloads)

Which destination directory do you want ? The same as the AgentLancher.exe ? We have to add to the agent the default directory of the chromedriver, don't you think ?

**Comment by skokaina** [comment]
Let's go with 2.24, since we haven't tested the agent againt 2.25 yet
in $user.home/.toast directory is perfect, if we can include a jdk8 in the directory that would be perfect since some users might not have java installed on their machine.
Doing this, you'd need to change the command line to run the agent through for the AgentLauncher.exe (and a u :))

**Comment by NathCoco** [comment]
Ready to be pushed on master

**Comment by skokaina** [comment]
Please create a pull request

**Comment by NathCoco** [comment]
Commited on master

**Comment by NathCoco** [comment]
Commited on master
