### ISSUE TITLE
Improve test report design

### ISSUE THREAD

**Issue by nicosvg** [talan-labs/toast-tk-engine#4]
## Spelling
- Excution Date -> Execution date 
- Scénario -> Scenario
## Format
- format execution time: 1447854446090
- `Integrate *ProjetFlux[id='0', status='20']*` 
  - Simplify: details should be visible only on user action (click on _ProjectFlux_ for instance)

**Comment by skokaina** [comment]
Delivered with with #69 but ui-popover doesn't work for the time being
