### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by nicosvg** [talan-labs/toast-tk-engine#65]

**Comment by skokaina** [comment]
- [x] Webapp with user management: user will be able to request a trial, hence we shall be able to create user with a private API key to access the webapp rest services and track them in the logs
- [x] A user will be part of team and a team will own multiple projects that any report, test case, action will belong to
- [x] Only admin users will have access to user creation features, the roles will need to be double checked (front-end and backend)
- [x] A user shall be able to request a demo by providing his mail (mandatory: login, project name, optional: team size, project description, team name)

**Comment by skokaina** [comment]
When a user request an access, he will need to provide a project name

**Comment by tabkram** [comment]
Working on demo request : see #46
