### ISSUE TITLE
Project creation

### ISSUE THREAD

**Issue by nicosvg** [talan-labs/toast-tk-engine#73]
The user should be able to create a project.
Attributes : 
- name
- description
  No need for edition of already created now.

**Comment by nicosvg** [comment]
See http://blog.mongodb.org/post/87200945828/6-rules-of-thumb-for-mongodb-schema-design-part-1 for schema

**Comment by skokaina** [comment]
Administrate User Groups mapping with projects (long run)

**Comment by skokaina** [comment]
75-project-creation branch (typo: 73-*)

**Comment by skokaina** [comment]
merged in to master on gitlab

**Comment by skokaina** [comment]
final size: 13 (#8)
