### ISSUE TITLE
Agent API Key

### ISSUE THREAD

**Issue by skokaina** [talan-labs/toast-tk-engine#79]
- [x] Set the Api Key (lisence version) in the Agent Settings
- [ ] Update all REST calls to include the API Key

**Comment by skokaina** [comment]
Try closing connections

**Comment by skokaina** [comment]
check HttpCloseable for more information

**Comment by NathCoco** [comment]
Is the Api Key a string ?

**Comment by skokaina** [comment]
Yes it's a string

**Comment by NathCoco** [comment]
Branch merge request : 79-agent-api-key

**Comment by NathCoco** [comment]
@skokaina have the hand. 
I can help you now if you need.

**Comment by skokaina** [comment]
The attribute to use in the http header for any request from the agent to the webapp must be named: "Token"
Dans la class RestUtils, ajouter le parametre token au méthodes:
- postWebEventRecord
- registerAgent

Dans chaque methode, intégrer la valeur dans le header du httpClient ("Token")
