### ISSUE TITLE
Agent Windows Installer

### ISSUE THREAD

**Issue by skokaina** [talan-labs/toast-tk-engine#82]
Create a windows installer for the agent
needs to be deployable on 32 and 64 bit

**Comment by NathCoco** [comment]
Where do I have to deploy the run-agen.exe ?
In "C:\Program Files\ToastTK-Agent\" ?

**Comment by skokaina** [comment]
we can deploy it by default there, usually the wizard should allow the user to override the installation folder

**Comment by NathCoco** [comment]
Commit on branch 82-agent-installer
To try it you need to add the agent standalone in "ressources" (Cf toast-tk-agent-setup\README.txt)

**Comment by NathCoco** [comment]
Tested on Sandrine's CPU : OK.
