### ISSUE TITLE
Persisting reports to MySql

### ISSUE THREAD

**Issue by cyterdan** [talan-labs/toast-tk-engine#83]
Hello

We'd like to persist reports to a MySQL table instead of MongoDB. 
Do you plan on developing integration with relational databases ? 
If not, what would be a simple way of implementing this ? 
Thanks

**Comment by skokaina** [comment]
Hi cyterdan,

For the time being, there's no plan to persist test reports to MySQL databases. 
Still, it's a feature we'll be looking to integrate in the future.
The best way to do it would be through the creation of a dedicated maven module: "toast-tk-dao-sql".
This module can share service interfaces with "toast-tk-dao" through "toast-tk-dao-api.

By the way, in which case do you need to store reports to MySQL ? MongoDB isn't helpful to you ?

**Comment by cyterdan** [comment]
We had a preference for MySQL but settled for using MongoDB for now.

**Comment by skokaina** [comment]
@cyterdan issue closed as you will stick with MongoDB
