### ISSUE TITLE
Test isolation in campaign

### ISSUE THREAD

**Issue by cyterdan** [talan-labs/toast-tk-engine#84]
When running a campaign with multiple web tests. The campaign fails if one of the tests closes the browser at the end. I get this error `Using WebDriver after calling quit()`

The tests apparently share the same webdriver session.
Is this the expected behavior ? 

Thanks

**Comment by skokaina** [comment]
For the time being, the "Close browser" action calls the "quit()" method.  
Hence, it kills the webdriver session. The error you get is the expected behavior.
What are you looking to test ? 
Do you need multiple session support or just closing and opening back the browser ?

**Comment by cyterdan** [comment]
My use case is running a project with multiple web scenarios :  

```
|| campaign || multiple ||
| scenario1 | scenario1.script |
| scenario2 | scenario2.script |
```

scenario1.script  : 

```
| Naviguer vers *http://www.google.fr/* |
| Fermer le navigateur |

```

scenario2.script : 

```
| Naviguer vers *http://www.google.com/* |
| Fermer le navigateur |
```

When running the campaign (with CIMongoStorageProjectRunner in the examples), it fails (the driver is reused between runs.

I have a fix for this and can submit a PR to toast-tk-selenium-plugin (if this is a indeed a bug of course)

**Comment by skokaina** [comment]
Sure, please submit your PR, we'll have a look..

**Comment by skokaina** [comment]
@cyterdan this issue will be closed, you can re-open a new one if you are still experiencing this with v0.1.5
